### ISSUE TITLE
mzML files and Linux

### ISSUE THREAD

**Issue by lopippo** [michaelmarty/UniDec#42]
Greetings, 

If I converted Synapt2 raw files to mzML using ProteoWizard's msConvert, would I be able to use UniDec on Linux exactly as I would on Windows ?

I looked at the code and it really seems that it is portable Python and C/++.

Could you confirm this, or list the features that would miss ? In particular, what features are available thanks to the use of the Waters library that would not if using mzML files (if any)?

Thank your very much for sharing this Free Software piece of work.

lopippo

**Comment by michaelmarty** [comment]
Hi Iopippo,
Good to hear from you. It's been a year or 2 since I tested it on Linux, but I think the mzML should work well on Linux.  Everything should run fine, and the only features that should be missing are the native Thermo/Waters/Agilent file opening. As long as you have it in mzML, everything else should be the same. The only thing you will lose from converting it to mzML is the IM data. Otherwise, everything else should be the same. In theory, there is a way to do ion mobility and mzML, but I'm not sure how it works. 
Also, for installing things on Linux, take a look at this file: https://github.com/michaelmarty/UniDec/blob/master/unidec_src/linux_dependencies.sh. It should install everything you need for UniDec to run, but it might be a little outdated. I haven't tested it in a few years. If you get a similar shell script working, let me know and we can update it here. Let me know if you have other questions. Thanks, MTM

**Comment by lopippo** [comment]
Greetings, Michael,

Synapt 2 files are successfully converted by msconvert to mzML files that contain drift time data that are perfectly usable.
Thank you for your answer. We can close this isssue.
