### ISSUE TITLE
error with opening .raw files 

### ISSUE THREAD

**Issue by BrBella** [michaelmarty/UniDec#68]
Hi Michael,
I have a problem with opening raw files with unidec. Other file formats (.txt) are ok, but it crushes even if I try to open the example data .raw file. 
I have the same issue on my laptop (intel i5 cpu, 16gb RAM) and on the workstation (intel xeon cpu, 128 GB RAM) as well.
Thanks,
Bella

**Comment by michaelmarty** [comment]
Hi Bella,
Thanks for reaching out have you tried this?

Important Note: If you are having issues where it crashes when opening Thermo files, it may be because the security settings are blocking parts of the software. To fix this, delete the unzipped folder, right click on the zip file, select Properties, and click unblock. You can then unzip the file again, and it should work.

Thanks,
MTM

**Comment by BrBella** [comment]
Hi Michael,
thanks a lot, now it works! Only one problem remained: I can not open
bigger files (in 300-400 MB mzml or raw format) because Unidec wants to
consume all the available RAM memory (128 GB).
Do you have any idea why?
Thank you for all of your help!
Best,
Bella

michaelmarty ***@***.***> ezt írta (időpont: 2022. júl. 18.,
H, 17:18):

**Comment by michaelmarty** [comment]
Great! Weird. My laptop with only 16 GB RAM is able to open files at least 800 MB in size. I think it should work on much larger, but that's all I could find to test this morning. Can you send me an example file to test on? The mzML importer in particular should be able to handle large file. Thanks,
MTM

**Comment by BrBella** [comment]
Hi Michael,
it seems I made a mistake when I exported the spectrum from freestyle, now
unidec works fine.
Thank you very much for your help and time!
Best,
Bella

michaelmarty ***@***.***> ezt írta (időpont: 2022. júl. 19.,
K, 18:16):

**Comment by michaelmarty** [comment]
Happy to help! Let me know if anything else comes up. Thanks,
MTM
